# fly.toml file generated for floral-feather-5562 on 2021-09-17T11:57:02+02:00

app = "floral-feather-5562"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]

[deploy]
  release_command = "eval NotebookGarden.Release.migrate"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
    method = "get"
    path = "/"
    protocol = "http"
